services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: readfolio_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/readfolio_development
      RAILS_ENV: development
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FRONTEND_URL: http://${FRONTEND_HOST:-localhost}:${FRONTEND_PORT:-5173}
      BACKEND_URL: http://${BACKEND_HOST:-localhost}:${BACKEND_PORT:-3000}
    volumes:
      - ./backend:/app
      - bundle_cache:/usr/local/bundle
      - /app/tmp
      - /app/log
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      VITE_API_URL: http://${BACKEND_HOST:-localhost}:${BACKEND_PORT:-3000}
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle_cache:
  node_modules: 